<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a0c470e7-3ac8-4ec6-90ac-1218562d4bed</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\icons\" />
    <Folder Include="wwwroot\fonts\" />
    <Folder Include="wwwroot\img\categories\" />
    <Folder Include="wwwroot\img\logo\" />
    <Folder Include="wwwroot\img\icons\" />
    <Folder Include="wwwroot\js\wwwroot\js\" />
    <Folder Include="wwwroot\videos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.*" />
  </ItemGroup>

</Project>
